yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "local-pack@*":
    dependencies:
      "happy-dom": "^14.12.3"
  "swiper@*":
    dependencies:
      "react": "^18.3.1"
  "@aws-sdk/core@*":
    dependencies:
      "tslib": "*"
  "react-intersection-observer@*":
    dependencies:
      "react-dom": "*"
